---
- name: Add PostgreSQL APT repository
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main'
    state: present
    filename: 'pgdg.list'

- name: Add PostgreSQL APT key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Ensure PostgreSQL is installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - postgresql-16
    - postgresql-client-16

- name: Ensure PostgreSQL service is enabled and started
  systemd:
    name: postgresql
    enabled: yes
    state: started

- name: Configure PostgreSQL
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/16/main/postgresql.conf
  notify:
    - Restart PostgreSQL
